### ISSUE TITLE
Adaptation for medical images

### ISSUE THREAD

**Issue by txusser** [StefanoD/ExactHistogramMatching#3]
Hi,

I have been trying (unsuccessfully) to use your code for the histogram matching of medical images. I obtain as a result the exact same input image. I am passing a 120x120x100 matrix. Anyclue what can be happening?

**Comment by StefanoD** [comment]
Hi,
could you provide code and the image, please? I could look into it at weekend. 😊

**Comment by txusser** [comment]
Hi Stefano,

Thank u for your quick response 💃 . In the code down bellow, you can find:

1) a simple python function on how to read the provided images and do conventional histogram matching. Just for reference on how to load Nifti images. 
2) The second function is how I was trying to provide data to your code.

I also provide 2 images in Nifti format.

I know that the code would need adaptation to work with 3d matrices, but I was expecting to have some preliminary results to see how it works and then continue with the adaptation. Unfortunately, I am obtaining the exact source image as an output. 

[reference.nii.gz](https://github.com/StefanoD/ExactHistogramSpecification/files/3880496/reference.nii.gz)
[source.nii.gz]
(https://github.com/StefanoD/ExactHistogramSpecification/files/3880497/source.nii.gz)

If you are willing to adapt your code to work with medical images, I think that this would be very helpful. If you want, I can share my work with you so you have a better idea of the problem 👍 

Cheers
---------------------------------------------------------
import nibabel as nib
import numpy as np
from histogram_matching import ExactHistogramMatcher

def histogram_matching(reference_nii, input_nii, output_nii):

    # Load the template image
    template = nib.load(reference_nii)
    nt_data = template.get_data()[:,:,:]

    # Load the patient image
    patient = nib.load(input_nii)
    pt_data = patient.get_data()[:,:,:]

    # Stores the image data shape that will be used later
    oldshape = pt_data.shape

    # Converts the data arrays to single dimension and normalizes by the maximum
    nt_data_array = nt_data.ravel()
    pt_data_array = pt_data.ravel()

    # get the set of unique pixel values and their corresponding indices and counts
    s_values, bin_idx, s_counts = np.unique(pt_data_array, return_inverse=True, return_counts=True)
    t_values, t_counts = np.unique(nt_data_array, return_counts=True)

    # take the cumsum of the counts and normalize by the number of pixels to
    # get the empirical cumulative distribution functions for the source and
    # template images (maps pixel value --> quantile)
    s_quantiles = np.cumsum(s_counts).astype(np.float64)
    s_quantiles /= s_quantiles[-1]
    t_quantiles = np.cumsum(t_counts).astype(np.float64)
    t_quantiles /= t_quantiles[-1]

    # interpolate linearly to find the pixel values in the template image
    # that correspond most closely to the quantiles in the source image
    interp_t_values = np.interp(s_quantiles, t_quantiles, t_values)

    #Reshapes the corresponding values to the indexes and reshapes the array to input
    final_image_data = interp_t_values[bin_idx].reshape(oldshape)

    #Saves the output data
    img = nib.Nifti1Image(final_image_data, patient.affine, patient.header)
    nib.save(img, output_nii)

    return output_nii

def exact_histogram_matching(reference_nii, input_nii, output_nii):

    
    # Load the template image
    template = nib.load(reference_nii)
    nt_data = template.get_data()[:,:,:]

    # Load the patient image
    patient = nib.load(input_nii)
    pt_data = patient.get_data()[:,:,:]

    reference_histogram = ExactHistogramMatcher.get_histogram(nt_data)

    matched_img = ExactHistogramMatcher.match_image_to_histogram(pt_data, reference_histogram)

    img = nib.Nifti1Image(matched_img, patient.affine, patient.header)
    nib.save(img, output_nii)

**Comment by StefanoD** [comment]
Hi,
would it be possible to provide a complete example? 
As far as I can tell you provided me a reference image, but not the target image that should be matched to the reference histogram.

A complete running program with all necesarry data would be helpful. 🙂

**Comment by txusser** [comment]
Hi again Stefano:

Let's try again :D. In the zip file, you can find 3 (.nii) files that are nifti images (reference.nii, source.nii and histogram_matched.nii) and 3 python files:

histogram_matching.py - Conventional histogram matching example
exact_histogram_matching.py - Histogram matching using your code

Running any of these codes will produce a new histogram_matched.nii. Just uncompress and run. I also added a plot_histograms.py that will display the resulting histograms.

Just a limitation, my original codes histogram_matching.py and plot_histograms.py are in Python 2.

If you have any doubts or need help don't hesitate to contact me on Skype (jesus.silva_r)

Cheers, 

[Desktop.zip](https://github.com/StefanoD/ExactHistogramSpecification/files/3882506/Desktop.zip)

**Comment by StefanoD** [comment]
Hi,
the problem is, that your image has floating point numbers and my lib can't handle it when it calculates the histogram, because it assumes integer values. So you get a reference histogram with the value 0.

One way to solve this, is to rescale your image to 8 bit or 10 bit.
First try to rescale it to 8 bit and if this works, than try 10 bit for higher accuracy.

For 10 bit use the second parameter:

```python
reference_histogram = ExactHistogramMatcher.get_histogram(nt_data, 10)
```

Edit: I updated my example file, because it didn't work anymore with the latest scipy version.

**Comment by StefanoD** [comment]
You can rescale like this:


```python
scaled_nt_data = np.round(255 * (nt_data / np.max(nt_data)))
scaled_nt_data = np.asarray(scaled_nt_data, np.uint8)

reference_histogram = ExactHistogramMatcher.get_histogram(scaled_nt_data)
```

**Comment by txusser** [comment]
Hi Stefano,

I have tried it and it works like a charm. Thanks a lot!

**Comment by StefanoD** [comment]
You're welcome! 😊
