### ISSUE TITLE
Too much white output

### ISSUE THREAD

**Issue by raoumairwaheed** [StefanoD/ExactHistogramMatching#4]
Hi sir, I am using your code but not getting the correct output. The output image is too much white.
please tell me if I am doing something wrong. Also, I have a deadline in two days. Please help me as early as possible. Thank you

![Capture](https://user-images.githubusercontent.com/61234793/81228137-f69e6280-9006-11ea-99f7-89ac1f13845d.PNG)

**Comment by StefanoD** [comment]
Hi,
I can't tell, because I don't know your code, nor do I have your images.
You can attach them here, if you want.
Are you sure, that target image and reference image have the same dimensions?

**Comment by StefanoD** [comment]
See also this issue: https://github.com/StefanoD/ExactHistogramSpecification/issues/3#issuecomment-557894342

**Comment by raoumairwaheed** [comment]
yes both the images have the same dimensions, I also used your images, and that is the result I got


![image](https://user-images.githubusercontent.com/61234793/81228903-55181080-9008-11ea-94ea-8ed93e4a8ed7.png)

**Comment by StefanoD** [comment]
Could you attach your images?

**Comment by raoumairwaheed** [comment]
here are my images

[GreyValue.zip](https://github.com/StefanoD/ExactHistogramSpecification/files/4589505/GreyValue.zip)

**Comment by StefanoD** [comment]
I don't know what your problem is:
![grey_out](https://user-images.githubusercontent.com/1634862/81230169-440fd500-8ff1-11ea-920a-0984137d0c7d.png)

This is my code:
```python
def histogram_matching_grey_values():
    target_img = imageio.imread('/home/stefano/test/target.jpg')
    reference_img = imageio.imread('/home/stefano/test/ref.jpg')

    reference_histogram = ExactHistogramMatcher.get_histogram(reference_img)
    new_target_img = ExactHistogramMatcher.match_image_to_histogram(target_img, reference_histogram)
    imageio.imsave('grey_out.png', new_target_img)
```

**Comment by raoumairwaheed** [comment]
problem was with opencv.imshow. my issue is resolved now. thankyou so much for your response
![image](https://user-images.githubusercontent.com/61234793/81231179-2bf97f00-900c-11ea-9bc6-23ec2d735cf3.png)

**Comment by StefanoD** [comment]
Ok, nice to here.
I would like to here some feedback from you.
For what are you using my lib and in which industry are you working?

**Comment by raoumairwaheed** [comment]
I am a student of MS CS. I have an assignment of Digital Image Processing in which I have a question regarding Exact Histogram Specification. And your code helps me very much.
Thank you so much.
